# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.locale: en|sk
    app.emails.contact_email: adam.benovic@bootiq.io

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    # controllers
    App\Controller\HomePageController:
        public: true
        arguments:
            $formHandler: '@app.form_handler'
            $postsLoading: '@app.posts_loading'
    App\Controller\BlogController:
        public: true
        arguments:
            $formHandler: '@app.form_handler'
            $postsLoading: '@app.posts_loading'
        tags: ['controller.service_arguments']
    App\Controller\LocaleSwitchController:
        public: true
        tags: ['controller.service_arguments']

    #repositories
    App\Repository\BlogRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags:
            - 'doctrine.repository_service'
    App\Repository\CommentRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags:
            - 'doctrine.repository_service'

    #listeners
    app.locale_listener:
        class: App\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    #handlers
    app.form_handler:
        class: App\Service\FormHandler
        arguments:
            $formFactory: '@form.factory'
            $flashBag: '@session.flash_bag'
            $mailer: '@swiftmailer.mailer.default'
            $twig: '@templating.engine.twig'
            $params: '@parameter_bag'
            $security: '@security.helper'
            $postsLoading: '@app.posts_loading'
        tags:
            - { name: form_handler }
    app.posts_loading:
        class: App\Service\PostsLoading
        arguments:
            $em: '@doctrine.orm.default_entity_manager'
            $security: '@security.helper'
        tags:
            - { name: posts_loading }