# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.locale: en|sk
    app.contact_email: adam.benovic@bootiq.io

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    # controllers
    App\Controller\HomePageController:
        public: true
        arguments:
            $contactHandler: '@App\Handler\ContactFormHandler'
            $dbService: '@App\Service\DatabaseService'
    App\Controller\BlogController:
        public: true
        arguments:
            $dbService: '@App\Service\DatabaseService'
            $commentHandler: '@App\Handler\CommentFormHandler'
            $addPostHandler: '@App\Handler\AddPostFormHandler'
            $editPostHandler: '@App\Handler\EditPostFormHandler'
        tags: ['controller.service_arguments']
    App\Controller\LocaleSwitchController:
        public: true
        tags: ['controller.service_arguments']

    #repositories
    App\Repository\BlogRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags:
            - 'doctrine.repository_service'
    App\Repository\CommentRepository:
        arguments:
            $registry: '@Symfony\Bridge\Doctrine\RegistryInterface'
        tags:
            - 'doctrine.repository_service'

    #listeners
    App\EventListener\LocaleListener:
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    #handlers
    App\Handler\AddPostFormHandler:
        arguments:
            $formFactory: '@form.factory'
            $security: '@security.helper'
            $blogRepo: '@App\Repository\BlogRepository'
        tags:
            - { name: add_post_handler }
    App\Handler\CommentFormHandler:
        arguments:
            $formFactory: '@form.factory'
            $flashBag: '@session.flash_bag'
            $security: '@security.helper'
            $commentRepo: '@App\Repository\CommentRepository'
        tags:
            - { name: comment_handler }
    App\Handler\ContactFormHandler:
        arguments:
            $formFactory: '@form.factory'
            $flashBag: '@session.flash_bag'
            $mailer: '@Swift_Mailer'
            $twig: '@templating'
            $mailTo: '%app.contact_email%'
        tags:
            - { name: contact_handler }
    App\Handler\EditPostFormHandler:
        arguments:
            $formFactory: '@form.factory'
            $blogRepo: '@App\Repository\BlogRepository'
        tags:
            - { name: edit_post_handler }

    #services
    App\Service\DatabaseService:
        arguments:
            $em: '@Doctrine\ORM\EntityManagerInterface'
            $security: '@security.helper'
            $blogRepo: '@App\Repository\BlogRepository'
            $commentRepo: '@App\Repository\CommentRepository'
        tags:
            - { name: db_service }